---

# windows
windows_source_dir: C:\_sources
windows_apps_dir: C:\_apps

# https://kb.firedaemon.com/support/solutions/articles/4000121705-openssl-binary-distributions-for-microsoft-windows#Download-OpenSSL
windows_openssl_package_url: https://download.firedaemon.com/FireDaemon-OpenSSL/openssl-3.4.1.zip
windows_openssl_apps_dir: "{{ windows_apps_dir }}\\{{ windows_openssl_package_url | basename | splitext | first }}"

windows_tls_dir: C:\_apps\tls
windows_tls_private_pem: C:\_apps\tls\private.pem
windows_tls_public_pem: C:\_apps\tls\public.pem
windows_tls_csr: C:\_apps\tls\server.csr
windows_tls_cer: C:\_apps\tls\server.cer

# linux
linux_source_dir: /tmp
linux_apps_dir: /apps


