---

- name: Windows
  when: ansible_system == "Win32NT"
  block:
    - name: Windows - OpenSSL
      ansible.builtin.include_tasks: windows/openssl.yaml

    - name: Windows - TLS Key
      ansible.builtin.include_tasks: windows/tls-key.yaml

    - name: Windows - Certificate Signing Request
      ansible.builtin.include_tasks: windows/tls-csr.yaml

# # Linux
# - name: Linux - OpenSSL
#   ansible.builtin.include_tasks: linux/openssl.yaml
#   when: ansible_system == "Linux"
