---

- name: Windows
  when: ansible_system == "Win32NT"
  block:
    - name: Windows - OpenSSL Installation
      ansible.builtin.include_tasks: windows/openssl.yaml

    - name: Windows - Generate TLS Private Key
      ansible.builtin.include_tasks: windows/tls-private-key.yaml

    - name: Windows - Generate Certificate Signing Request
      ansible.builtin.include_tasks: windows/tls-csr.yaml

# # Linux
# - name: Linux - OpenSSL
#   ansible.builtin.include_tasks: linux/openssl.yaml
#   when: ansible_system == "Linux"
