---

- name: Windows
  when: ansible_system == "Win32NT"
  block:
    - name: Windows - OpenSSL
      ansible.builtin.import_tasks: windows/openssl.yaml

    - name: Windows - TLS Key
      ansible.builtin.include_tasks: windows/tls-key.yaml

    - name: Windows - Certificate Signing Request
      ansible.builtin.include_tasks: windows/tls-csr.yaml

- name: Linux
  when: ansible_system == "Linux"
  block:
    - name: Linux - OpenSSL
      ansible.builtin.include_tasks: linux/openssl.yaml

    - name: Linux - TLS Key
      ansible.builtin.include_tasks: linux/tls-key.yaml

    - name: Linux - Certificate Signing Request
      ansible.builtin.include_tasks: linux/tls-csr.yaml
