---

- name: Windows
  when: ansible_system == "Win32NT"
  block:
    - name: Windows - OpenSSL
      ansible.builtin.include_tasks: windows/openssl.yaml

    - name: Windows - TLS Key
      ansible.builtin.include_tasks: windows/tls-key.yaml

    - name: Windows - Certificate Signing Request
      ansible.builtin.include_tasks: windows/tls-csr.yaml

- name: Linux
  when: ansible_system == "Linux"
  block:
    - name: Linux - OpenSSL
      ansible.builtin.include_tasks: linux/openssl.yaml

    - name: Linux TLS Key - Ensure tls directory exists
      become: true
      ansible.builtin.file:
        path: "{{ linux_tls_dir }}"
        state: directory
        owner: sergeiwaigant
        group: sergeiwaigant
        mode: '0700'

    - name: Linux - TLS Key and CSR
      ansible.builtin.include_tasks: linux/tls-key-csr.yaml
      loop: "{{ tls_cns }}"
      loop_control:
        loop_var: __tls_cn
        label: "{{ __tls_cn }}"

...
