---

- name: Windows TLS Key - Ensure tls directory exists
  ansible.windows.win_file:
    path: "{{ windows_tls_dir }}"
    state: directory

- name: Windows TLS Key - genrsa private key
  environment:
    PATH: "{{ windows_openssl_apps_dir }}\\x64\\bin"
  ansible.windows.win_command:
    chdir: "{{ windows_tls_dir }}"
    creates: "{{ windows_tls_dir }}\\private.pem"
    cmd: openssl genrsa -out private.pem 2048
  changed_when: false

- name: Windows TLS Key - genrsa pub key
  environment:
    PATH: "{{ windows_openssl_apps_dir }}\\x64\\bin"
  ansible.windows.win_command:
    chdir: "{{ windows_tls_dir }}"
    creates: "{{ windows_tls_dir }}\\pub.pem"
    cmd: openssl rsa -in private.pem -pubout -out pub.pem
  changed_when: false
