---

- name: Windows TLS Key - Ensure tls directory exists
  ansible.windows.win_file:
    path: "{{ windows_tls_dir }}"
    state: directory

- name: Windows TLS Key - genrsa private pem
  environment:
    PATH: "{{ windows_openssl_apps_dir }}\\x64\\bin"
  ansible.windows.win_command:
    chdir: "{{ windows_tls_dir }}"
    creates: "{{ windows_tls_private_pem }}"
    cmd: >
      openssl genrsa 2048
      -out {{ windows_tls_private_pem | basename }}
  changed_when: false

- name: Windows TLS Key - genrsa public pem
  environment:
    PATH: "{{ windows_openssl_apps_dir }}\\x64\\bin"
  ansible.windows.win_command:
    chdir: "{{ windows_tls_dir }}"
    creates: "{{ windows_tls_public_pem }}"
    cmd: >
      openssl rsa
      -in {{ windows_tls_private_pem | basename }}
      -pubout -out {{ windows_tls_public_pem | basename }}
  changed_when: false
