---

- name: OpenSSL Windows - Download Package
  ansible.windows.win_get_url:
    url: "{{ windows_openssl_package_url }}"
    dest: "{{ windows_source_dir }}\\{{ windows_openssl_package_url | basename }}"

# - name: Install OpenSSL Package
#   ansible.windows.win_package:
#     path: "{{ windows_source_dir }}\\{{ tomcat_installer | basename }}"
#     state: present

# - name: Decompress Tomcat Archive to {{ windows_apps_dir }}
#   when: tomcat_archive | default("") | length > 0
#   community.windows.win_unzip:
#     src: "{{ windows_source_dir }}\\{{ tomcat_archive | basename }}"
#     dest: "{{ windows_apps_dir }}"

- name: Decompress OpenSSL Package
  ansible.windows.win_powershell:
    creates: "{{ windows_apps_dir }}\\openssl"
    script: >
      Expand-Archive
      -Path {{ windows_source_dir }}\{{ windows_openssl_package_url | basename }}
      -DestinationPath {{ windows_apps_dir }}\openssl
  register: _result_decompress

# - name: Decompress OpenSSL Package
#   ansible.windows.win_powershell:
#     creates: "{{ windows_apps_dir }}\\{{ windows_openssl_package_url | basename | splitext | first }}"
#     script: >
#       Expand-Archive
#       -Path {{ windows_source_dir }}\{{ windows_openssl_package_url | basename }}
#       -DestinationPath {{ windows_apps_dir }}\{{ windows_openssl_package_url | basename | splitext | first }}
#   register: _result_decompress

- name: Test OpenSSL execution
  environment:
    PATH: "{{ windows_apps_dir }}\\openssl\\x64\\bin"
  ansible.windows.win_command: openssl --version
  register: _result_openssl

- debug:
    var: _result_openssl
